/**
 * IGUAZÚ ASSIST — Base de Datos Central Unificada & Configuración de Marca
 * 
 * Única fuente de verdad para catálogo de atractivos, geolocalización,
 * disponibilidad horaria, motor inteligente y monetización.
 */

// ========================================================
// CONFIGURACIÓN CENTRALIZADA DE LA APLICACIÓN
// ========================================================
const CONFIG_APP = {
    nombre: "Iguazú Assist",
    lema: "Tu asistente turístico inteligente",
    ciudad: "Puerto Iguazú",
    provincia: "Misiones, Argentina",
    // Coordenadas centrales de referencia (Plaza San Martín, Centro)
    coordenadasCentro: { lat: -25.5979, lng: -54.5742 },
    version: "2.2.0"
};

// ========================================================
// CATÁLOGO COMPLETO DE LUGARES Y EXPERIENCIAS REALES
// ========================================================
const lugaresReales = [

    // ========================================================
    // 🌿 NATURALEZA & PARQUES
    // ========================================================

    {
        id: 1,
        nombre: "Parque Nacional Iguazú",
        categoria: "naturaleza",
        intereses: ["naturaleza", "fauna", "paseos"],
        icono: "🌊",
        descripcion: "Maravilla natural del mundo. Circuitos Superior, Inferior y pasarela hacia la majestuosa Garganta del Diablo.",
        ubicacion: "Parque Nacional Iguazú",
        direccion: "Ruta 101 Km 142, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.6953, lng: -54.4367 },
        tipo: "Parque Nacional",
        horario: "08:00 a 18:00 (ingreso hasta las 16:30)",
        rangoHorario: { apertura: 8, cierre: 18 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Entrada oficial según residencia",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 5,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "mediodía"],
        prioridad: 10,
        destacado: true,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757491469",
        whatsapp: "",
        web: "https://iguazuargentina.com/",
        etiquetas: ["Imperdible", "Cataratas", "Patrimonio UNESCO", "Selva", "Fauna"]
    },

    {
        id: 2,
        nombre: "Güirá Oga (Casa de los Pájaros)",
        categoria: "naturaleza",
        intereses: ["naturaleza", "fauna", "actividades"],
        icono: "🦜",
        descripcion: "Centro de rescate, rehabilitación y reinserción de animales silvestres autóctonos de la selva misionera.",
        ubicacion: "Ruta 12 Km 1638",
        direccion: "Ruta Nacional 12 Km 1638, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.6268, lng: -54.5422 },
        tipo: "Refugio Silvestre & Educación",
        horario: "09:00 a 16:30",
        rangoHorario: { apertura: 9, cierre: 17 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Entrada arancelada con guía",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 2,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "tarde"],
        prioridad: 8,
        destacado: true,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757423908",
        whatsapp: "5493757548900",
        web: "https://guiraoga.com.ar/",
        etiquetas: ["Fauna", "Aves", "Educación", "Niños", "Rescate"]
    },

    {
        id: 3,
        nombre: "Jardín de los Colibríes",
        categoria: "naturaleza",
        intereses: ["naturaleza", "fauna", "paseos"],
        icono: "🐦",
        descripcion: "Santuario urbano donde decenas de especies de picaflores y aves autóctonas se alimentan en total libertad.",
        ubicacion: "Centro Residencial",
        direccion: "Fray Luis Beltrán 150, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.5978, lng: -54.5714 },
        tipo: "Jardín Botánico & Fauna",
        horario: "09:00 a 18:00",
        rangoHorario: { apertura: 9, cierre: 18 },
        diasApertura: [1, 2, 3, 4, 5, 6], // Martes a domingo
        precio: "Ingreso accesible",
        gratuito: false,
        nivelGasto: "economico",
        duracionHoras: 1,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "tarde"],
        prioridad: 7,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757422690",
        whatsapp: "",
        web: "",
        etiquetas: ["Aves", "Fotografía", "Tranquilo", "Colibríes"]
    },

    {
        id: 4,
        nombre: "Sendero Macuco y Salto Arrechea",
        categoria: "naturaleza",
        intereses: ["naturaleza", "paseos", "actividades"],
        icono: "🥾",
        descripcion: "Sendero peatonal de 3,5 km dentro de la selva virgen que culmina en una hermosa cascada con piletón natural.",
        ubicacion: "Dentro del Parque Nacional",
        direccion: "Acceso Parque Nacional Iguazú, Misiones",
        coordenadas: { lat: -25.6800, lng: -54.4450 },
        tipo: "Trekking & Selva",
        horario: "08:00 a 15:00 (último ingreso al sendero)",
        rangoHorario: { apertura: 8, cierre: 15 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Incluido en la entrada al Parque Nacional",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 3,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "amigos"],
        momentos: ["mañana", "tarde"],
        prioridad: 8,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "",
        whatsapp: "",
        web: "https://iguazuargentina.com/",
        etiquetas: ["Aventura", "Trekking", "Cascada", "Selva Profunda"]
    },

    {
        id: 5,
        nombre: "Salto del Turista",
        categoria: "naturaleza",
        intereses: ["naturaleza", "paseos"],
        icono: "🌿",
        descripcion: "Rincón natural oculto en Puerto Iguazú con un salto de agua ideal para desconectar y apreciar la flora nativa.",
        ubicacion: "Zona Costera",
        direccion: "Camino costero, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.5890, lng: -54.5680 },
        tipo: "Atractivo Natural Libre",
        horario: "Diurno (08:00 a 18:30)",
        rangoHorario: { apertura: 8, cierre: 18.5 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Acceso libre y gratuito",
        gratuito: true,
        nivelGasto: "economico",
        duracionHoras: 1.5,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "amigos"],
        momentos: ["mañana", "tarde"],
        prioridad: 6,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "",
        whatsapp: "",
        web: "",
        etiquetas: ["Agua", "Aire libre", "Gratuito", "Económico"]
    },

    {
        id: 25,
        nombre: "Costanera Eduardo Arrabal",
        categoria: "naturaleza",
        intereses: ["naturaleza", "paseos", "tres_paises"],
        icono: "🌅",
        descripcion: "Paseo ribereño sobre la costa del Río Iguazú con amplias veredas peatonales, bancos y vistas abiertas hacia el atardecer.",
        ubicacion: "Costanera Eduardo Arrabal",
        direccion: "Av. Costanera Eduardo Arrabal, Puerto Iguazú",
        coordenadas: { lat: -25.5935, lng: -54.5950 },
        tipo: "Paseo Ribereño & Espacio Público",
        horario: "Acceso libre las 24 hs (Recomendado atardecer)",
        rangoHorario: { apertura: 0, cierre: 24 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Acceso libre y gratuito",
        gratuito: true,
        nivelGasto: "economico",
        duracionHoras: 1.5,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "tarde", "atardecer", "noche"],
        prioridad: 8,
        destacado: true,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "",
        whatsapp: "",
        web: "",
        etiquetas: ["Río Iguazú", "Atardecer", "Caminata", "Gratuito", "Fotografía"]
    },

    {
        id: 30,
        nombre: "BioCentro Iguazú",
        categoria: "naturaleza",
        intereses: ["naturaleza", "fauna", "actividades"],
        icono: "🦋",
        descripcion: "Espacio temático con mariposario tropical, serpentario, acuario y orquidiario que exhibe la rica biodiversidad misionera.",
        ubicacion: "Ruta 12 Km 3.5",
        direccion: "Ruta Nacional 12 Km 3.5, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.6110, lng: -54.5570 },
        tipo: "Parque Temático de Biodiversidad",
        horario: "09:00 a 18:00",
        rangoHorario: { apertura: 9, cierre: 18 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Entrada arancelada",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 1.5,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "tarde"],
        prioridad: 7,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757422967",
        whatsapp: "",
        web: "https://biocentroiguazu.com/",
        etiquetas: ["Mariposario", "Reptiles", "Orquídeas", "Familia", "Fauna"]
    },

    {
        id: 33,
        nombre: "Paseo Ecológico en Balsas (Parque Nacional)",
        categoria: "naturaleza",
        intereses: ["naturaleza", "fauna", "actividades"],
        icono: "🚣",
        descripcion: "Navegación serena a remo en balsas por el Delta superior del Río Iguazú, avistando aves, tortugas y vegetación ribereña.",
        ubicacion: "Parque Nacional Iguazú",
        direccion: "Estación Garganta del Diablo, Parque Nacional Iguazú",
        coordenadas: { lat: -25.6940, lng: -54.4380 },
        tipo: "Navegación Ecológica Silenciosa",
        horario: "09:00 a 16:30",
        rangoHorario: { apertura: 9, cierre: 16.5 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Excursión arancelada (adicional)",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 1,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "mediodía", "tarde"],
        prioridad: 7,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757421662",
        whatsapp: "",
        web: "https://iguazujungle.com/",
        etiquetas: ["Delta", "Aves", "Navegación", "Tranquilo", "Cataratas"]
    },

    {
        id: 34,
        nombre: "Reserva Natural Selva Iryapú",
        categoria: "naturaleza",
        intereses: ["naturaleza", "paseos"],
        icono: "🌿",
        descripcion: "Área protegida de 600 hectáreas de selva nativa con senderos peatonales, comunidades originarias y lodges integrados al entorno.",
        ubicacion: "Selva Iryapú",
        direccion: "Acceso por Ruta 12 Km 3.5, Puerto Iguazú",
        coordenadas: { lat: -25.6150, lng: -54.5580 },
        tipo: "Reserva Natural de Selva",
        horario: "Libre acceso diurno (08:00 a 18:30)",
        rangoHorario: { apertura: 8, cierre: 18.5 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Acceso libre y gratuito",
        gratuito: true,
        nivelGasto: "economico",
        duracionHoras: 2,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "amigos", "familia"],
        momentos: ["mañana", "tarde"],
        prioridad: 7,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "",
        whatsapp: "",
        web: "",
        etiquetas: ["Selva Nativa", "Senderos", "Ecoturismo", "Gratuito"]
    },

    // ========================================================
    // 🎭 ACTIVIDADES, FERIAS, CULTURA & EXPERIENCIAS
    // ========================================================

    {
        id: 24,
        nombre: "Feria de la Plaza San Martín",
        categoria: "actividades",
        intereses: ["compras", "actividades", "paseos", "noche"],
        icono: "🎪",
        descripcion: "Feria artesanal y de emprendimientos locales en el corazón de Puerto Iguazú. Puestos de artesanías, recuerdos y productos regionales.",
        ubicacion: "Plaza San Martín (Centro)",
        direccion: "Plaza San Martín, Av. Victoria Aguirre y Av. Brasil, Puerto Iguazú",
        coordenadas: { lat: -25.5979, lng: -54.5742 },
        tipo: "Feria Artesanal & Emprendedores",
        horario: "18:00 a 22:00 todos los días",
        rangoHorario: { apertura: 18, cierre: 22 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Acceso libre y gratuito",
        gratuito: true,
        nivelGasto: "economico",
        duracionHoras: 1,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["atardecer", "noche"],
        prioridad: 9,
        destacado: true,
        patrocinado: false,
        promocion: "Feria nocturna diaria en la plaza principal",
        prioridadComercial: 1,
        telefono: "",
        whatsapp: "",
        web: "",
        etiquetas: ["Feria", "Artesanías", "Gratuito", "Centro", "Plaza San Martín", "Emprendimientos"]
    },

    {
        id: 6,
        nombre: "Hito Tres Fronteras",
        categoria: "actividades",
        intereses: ["actividades", "tres_paises", "paseos", "noche"],
        icono: "🌎",
        descripcion: "Mirador icónico con vista panorámica de la confluencia entre los ríos Iguazú y Paraná, uniendo Argentina, Brasil y Paraguay.",
        ubicacion: "Costanera y Tres Fronteras",
        direccion: "Av. Tres Fronteras y Costanera, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.5947, lng: -54.6067 },
        tipo: "Monumento & Mirador Panorámico",
        horario: "Abierto 24 hs (Feria y show de aguas desde las 19:30)",
        rangoHorario: { apertura: 0, cierre: 24 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Acceso libre y gratuito",
        gratuito: true,
        nivelGasto: "economico",
        duracionHoras: 1.5,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["tarde", "atardecer", "noche"],
        prioridad: 9,
        destacado: true,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "",
        whatsapp: "",
        web: "",
        etiquetas: ["Imperdible", "3 Países", "Atardecer", "Feria Artesanal", "Show de Aguas", "Gratuito"]
    },

    {
        id: 26,
        nombre: "Comunidad Mbyá Guaraní Yasy Porá",
        categoria: "actividades",
        intereses: ["actividades", "naturaleza", "paseos"],
        icono: "🛖",
        descripcion: "Experiencia cultural auténtica guiada por miembros de la comunidad: senderos por la selva, conocimiento de plantas medicinales, trampas ancestrales y artesanías.",
        ubicacion: "Reserva Selva Iryapú",
        direccion: "Reserva Selva Iryapú s/n, Puerto Iguazú",
        coordenadas: { lat: -25.6175, lng: -54.5520 },
        tipo: "Turismo Cultural Comunitario",
        horario: "09:00 a 17:00",
        rangoHorario: { apertura: 9, cierre: 17 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Bono contribución comunitario con guía local",
        gratuito: false,
        nivelGasto: "economico",
        duracionHoras: 2,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "tarde"],
        prioridad: 8,
        destacado: true,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "",
        whatsapp: "",
        web: "",
        etiquetas: ["Cultura Guaraní", "Comunidad Originaria", "Selva", "Senderos", "Artesanías"]
    },

    {
        id: 7,
        nombre: "La Aripuca",
        categoria: "actividades",
        intereses: ["actividades", "paseos", "naturaleza"],
        icono: "🌳",
        descripcion: "Impresionante estructura construida con troncos gigantes rescatados, inspirada en una trampa tradicional guaraní para concientizar sobre el cuidado ambiental.",
        ubicacion: "Ruta 12 Km 4.5",
        direccion: "Ruta Nacional 12 Km 4.5, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.6203, lng: -54.5469 },
        tipo: "Parque Cultural & Temático",
        horario: "09:00 a 18:00",
        rangoHorario: { apertura: 9, cierre: 18 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Entrada arancelada",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 1.5,
        alAireLibre: true,
        aptoPara: ["pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "tarde"],
        prioridad: 7,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757422340",
        whatsapp: "",
        web: "https://aripuca.com.ar/",
        etiquetas: ["Cultura Guaraní", "Artesanías", "Helado de Yerba Mate", "Familia"]
    },

    {
        id: 27,
        nombre: "Museo Imágenes de la Selva",
        categoria: "actividades",
        intereses: ["actividades", "paseos"],
        icono: "🗿",
        descripcion: "Espacio cultural que alberga la magnífica colección de esculturas en madera de Rodolfo Teófilo Allou retratando la fauna, leyendas y personajes misioneros.",
        ubicacion: "Ruta 12 Km 5",
        direccion: "Ruta Nacional 12 Km 5, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.6190, lng: -54.5450 },
        tipo: "Museo de Esculturas & Cultura",
        horario: "08:00 a 18:00",
        rangoHorario: { apertura: 8, cierre: 18 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Entrada accesible",
        gratuito: false,
        nivelGasto: "economico",
        duracionHoras: 1.5,
        alAireLibre: false,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "tarde"],
        prioridad: 7,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757420600",
        whatsapp: "",
        web: "",
        etiquetas: ["Museo", "Cultura", "Esculturas", "Madera", "Ideal Lluvia"]
    },

    {
        id: 28,
        nombre: "Paseo de los Artesanos de la Costanera",
        categoria: "actividades",
        intereses: ["compras", "actividades", "paseos"],
        icono: "🛍️",
        descripcion: "Puestos de artesanos locales y guaraníes situados en el camino panorámico hacia el Hito Tres Fronteras, con cestería, maderas talladas y recuerdos.",
        ubicacion: "Av. Tres Fronteras y Costanera",
        direccion: "Av. Tres Fronteras s/n, Puerto Iguazú",
        coordenadas: { lat: -25.5950, lng: -54.6040 },
        tipo: "Paseo de Artesanías al Aire Libre",
        horario: "16:00 a 22:00",
        rangoHorario: { apertura: 16, cierre: 22 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Acceso libre y gratuito",
        gratuito: true,
        nivelGasto: "economico",
        duracionHoras: 1,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["tarde", "atardecer", "noche"],
        prioridad: 7,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "",
        whatsapp: "",
        web: "",
        etiquetas: ["Feria", "Artesanías", "Compras", "Gratuito", "Costanera"]
    },

    {
        id: 8,
        nombre: "Iguazú Gran Aventura (Paseo Náutico)",
        categoria: "actividades",
        intereses: ["actividades", "naturaleza"],
        icono: "🚤",
        descripcion: "Emocionante navegación en lancha bimotor hasta los pies de los saltos San Martín y Tres Mosqueteros con bautismo de agua inolvidable.",
        ubicacion: "Interior del Parque Nacional",
        direccion: "Parque Nacional Iguazú, Misiones",
        coordenadas: { lat: -25.6880, lng: -54.4410 },
        tipo: "Aventura Náutica en Cataratas",
        horario: "09:00 a 16:00",
        rangoHorario: { apertura: 9, cierre: 16 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Consultar tarifa oficial de excursión",
        gratuito: false,
        nivelGasto: "alto",
        duracionHoras: 2.5,
        alAireLibre: true,
        aptoPara: ["pareja", "familia", "amigos"],
        momentos: ["mañana", "tarde"],
        prioridad: 9,
        destacado: true,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757421662",
        whatsapp: "5493757520033",
        web: "https://iguazujungle.com/",
        etiquetas: ["Adrenalina", "Cataratas", "Paseo en Lancha", "Aventura", "Agua"]
    },

    {
        id: 31,
        nombre: "Iguazú Forest (Canopy & Rappel)",
        categoria: "actividades",
        intereses: ["actividades", "naturaleza"],
        icono: "🧗",
        descripcion: "Circuito de turismo aventura en selva virgen: tirolesa entre las copas de los árboles, rappel asistido en salto de agua y trekking.",
        ubicacion: "Ruta 12 Km 5",
        direccion: "Ruta Nacional 12 Km 5, Puerto Iguazú",
        coordenadas: { lat: -25.6250, lng: -54.5380 },
        tipo: "Aventura en Selva & Ecoturismo",
        horario: "08:30 a 17:00 (Turnos programados)",
        rangoHorario: { apertura: 8.5, cierre: 17 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Excursión arancelada con guías e instructores",
        gratuito: false,
        nivelGasto: "alto",
        duracionHoras: 3.5,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "amigos"],
        momentos: ["mañana", "tarde"],
        prioridad: 8,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757422320",
        whatsapp: "",
        web: "https://iguazuforest.com/",
        etiquetas: ["Tirolesa", "Rappel", "Aventura", "Adrenalina", "Selva"]
    },

    {
        id: 9,
        nombre: "Duty Free Shop Puerto Iguazú",
        categoria: "actividades",
        intereses: ["compras", "actividades", "paseos"],
        icono: "🛍️",
        descripcion: "Centro de compras libre de impuestos ambientado temáticamente con ciudades del mundo, perfumería, electrónica, moda y chocolates.",
        ubicacion: "Paso de Frontera",
        direccion: "Ruta Nac. 12 Km 1645 (Paso de Frontera), Puerto Iguazú",
        coordenadas: { lat: -25.5990, lng: -54.5850 },
        tipo: "Paseo Comercial Cubierto",
        horario: "12:00 a 20:00",
        rangoHorario: { apertura: 12, cierre: 20 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Entrada libre",
        gratuito: true,
        nivelGasto: "medio",
        duracionHoras: 2.5,
        alAireLibre: false,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["tarde", "noche"],
        prioridad: 8,
        destacado: true,
        patrocinado: false,
        promocion: "Paseo totalmente techado y climatizado",
        prioridadComercial: 1,
        telefono: "+543757421000",
        whatsapp: "",
        web: "https://www.dutyfreeshoppuertoiguazu.com/",
        etiquetas: ["Ideal Lluvia", "Compras", "Techado", "Climatizado", "Frontera"]
    },

    {
        id: 29,
        nombre: "Punto Iguazú Shopping Mall",
        categoria: "actividades",
        intereses: ["compras", "actividades", "comida"],
        icono: "🛍️",
        descripcion: "Centro comercial a cielo abierto con locales de marcas reconocidas, diseño, cafeterías al aire libre y opciones gastronómicas.",
        ubicacion: "Av. Victoria Aguirre",
        direccion: "Av. Victoria Aguirre 1338, Puerto Iguazú",
        coordenadas: { lat: -25.6065, lng: -54.5645 },
        tipo: "Centro Comercial a Cielo Abierto",
        horario: "10:00 a 22:00",
        rangoHorario: { apertura: 10, cierre: 22 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Acceso libre",
        gratuito: true,
        nivelGasto: "medio",
        duracionHoras: 2,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["tarde", "noche"],
        prioridad: 7,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757420100",
        whatsapp: "",
        web: "",
        etiquetas: ["Shopping", "Compras", "Cafeterías", "Gastronomía", "Moda"]
    },

    {
        id: 10,
        nombre: "Centro de Puerto Iguazú y La Feirinha",
        categoria: "actividades",
        intereses: ["compras", "comida", "paseos", "actividades"],
        icono: "🌴",
        descripcion: "Paseo céntrico con tiendas de artesanías, aceitunas rellenas, quesos, empanadas, vinos y ambiente típico y distendido.",
        ubicacion: "Avenida Brasil",
        direccion: "Av. Brasil y Av. Victoria Aguirre, Puerto Iguazú",
        coordenadas: { lat: -25.5983, lng: -54.5739 },
        tipo: "Paseo Urbano & Gastronómico",
        horario: "10:00 a 23:30",
        rangoHorario: { apertura: 10, cierre: 23.5 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Acceso libre",
        gratuito: true,
        nivelGasto: "economico",
        duracionHoras: 2,
        alAireLibre: false,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["tarde", "noche"],
        prioridad: 8,
        destacado: true,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "",
        whatsapp: "",
        web: "",
        etiquetas: ["Picadas", "Vinos", "Caminata", "Centro", "Compras", "Feirinha"]
    },

    {
        id: 32,
        nombre: "La Casa de las Botellas (Proyecto Ecológico)",
        categoria: "actividades",
        intereses: ["actividades", "paseos"],
        icono: "♻️",
        descripcion: "Emprendimiento sustentable con casas, muebles y juguetes fabricados íntegramente con botellas de plástico y materiales reciclados.",
        ubicacion: "Barrio Las Orquídeas",
        direccion: "Barrio Las Orquídeas, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.6120, lng: -54.5380 },
        tipo: "Proyecto Ecológico & Educativo",
        horario: "09:00 a 18:00",
        rangoHorario: { apertura: 9, cierre: 18 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Bono contribución accesible",
        gratuito: false,
        nivelGasto: "economico",
        duracionHoras: 1,
        alAireLibre: false,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "tarde"],
        prioridad: 6,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757422100",
        whatsapp: "",
        web: "",
        etiquetas: ["Reciclaje", "Educación", "Ecológico", "Familia", "Curiosidad"]
    },

    {
        id: 39,
        nombre: "Santuario Diocesano Virgen del Carmen",
        categoria: "actividades",
        intereses: ["actividades", "paseos"],
        icono: "⛪",
        descripcion: "Histórico templo diocesano frente a la Plaza San Martín, corazón espiritual y arquitectónico de la historia urbana de Puerto Iguazú.",
        ubicacion: "Centro",
        direccion: "Av. Victoria Aguirre y Av. Brasil (frente a Plaza San Martín)",
        coordenadas: { lat: -25.5976, lng: -54.5748 },
        tipo: "Templo Histórico & Patrimonio",
        horario: "08:00 a 12:00 y 16:00 a 20:00",
        rangosHorarios: [{ apertura: 8, cierre: 12 }, { apertura: 16, cierre: 20 }],
        rangoHorario: { apertura: 8, cierre: 20 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Acceso libre y gratuito",
        gratuito: true,
        nivelGasto: "economico",
        duracionHoras: 0.5,
        alAireLibre: false,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "tarde"],
        prioridad: 6,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757420141",
        whatsapp: "",
        web: "",
        etiquetas: ["Historia", "Patrimonio", "Centro", "Gratuito", "Tranquilo"]
    },

    // ========================================================
    // 🌙 NOCHE & ENTRETENIMIENTO
    // ========================================================

    {
        id: 11,
        nombre: "Paseo de Luna Llena en Cataratas",
        categoria: "noche",
        intereses: ["noche", "naturaleza"],
        icono: "🌕",
        descripcion: "Mágica excursión nocturna en tren ecológico hacia la Garganta del Diablo iluminada exclusivamente por la luz de la luna llena.",
        ubicacion: "Parque Nacional Iguazú",
        direccion: "Parque Nacional Iguazú, Misiones",
        coordenadas: { lat: -25.6953, lng: -54.4367 },
        tipo: "Experiencia Nocturna Exclusiva",
        horario: "Solo noches de plenilunio (turnos 19:45, 20:30, 21:15)",
        rangoHorario: { apertura: 19.5, cierre: 23 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Reserva previa requerida",
        gratuito: false,
        nivelGasto: "alto",
        duracionHoras: 3,
        alAireLibre: true,
        aptoPara: ["pareja", "familia", "amigos"],
        momentos: ["noche"],
        prioridad: 10,
        destacado: true,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757491469",
        whatsapp: "5493757520033",
        web: "https://iguazuargentina.com/paseo-luna-llena/",
        etiquetas: ["Exclusivo", "Luna Llena", "Romántico", "Imperdible", "Noche"]
    },

    {
        id: 12,
        nombre: "Icebar Iguazú (Bar de Hielo)",
        categoria: "noche",
        intereses: ["noche", "actividades"],
        icono: "🧊",
        descripcion: "Bar temático con barra y esculturas completamente talladas en hielo a -10 °C con barra libre de tragos e indumentaria provista.",
        ubicacion: "Ruta 12 Km 4.5",
        direccion: "Ruta Nacional 12 Km 4.5, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.6180, lng: -54.5470 },
        tipo: "Bar Temático de Hielo & Experiencia",
        horario: "14:00 a 00:00",
        rangoHorario: { apertura: 14, cierre: 24 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Incluye campera, guantes y barra libre",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 1.5,
        alAireLibre: false,
        aptoPara: ["pareja", "amigos", "familia", "niños"],
        momentos: ["tarde", "noche"],
        prioridad: 8,
        destacado: true,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 1,
        telefono: "+543757421100",
        whatsapp: "5493757670800",
        web: "https://icebariguazu.com/",
        etiquetas: ["Ideal Lluvia", "Tragos", "Diversión", "Noche", "Techado"]
    },

    {
        id: 13,
        nombre: "Show de Aguas Danzantes en Hito Tres Fronteras",
        categoria: "noche",
        intereses: ["noche", "tres_paises", "actividades"],
        icono: "⛲",
        descripcion: "Espectáculo audiovisual nocturno de luces, música folclórica y proyecciones de agua que representan la cultura de los 3 países.",
        ubicacion: "Hito Tres Fronteras",
        direccion: "Av. Tres Fronteras y Costanera, Puerto Iguazú",
        coordenadas: { lat: -25.5947, lng: -54.6067 },
        tipo: "Espectáculo Nocturno",
        horario: "Desde las 20:00 (turnos regulares)",
        rangoHorario: { apertura: 19.5, cierre: 22.5 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Acceso libre y gratuito",
        gratuito: true,
        nivelGasto: "economico",
        duracionHoras: 1,
        alAireLibre: true,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["noche"],
        prioridad: 8,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "",
        whatsapp: "",
        web: "",
        etiquetas: ["Luces", "Música", "Familiar", "Gratuito", "Noche", "Hito"]
    },

    {
        id: 37,
        nombre: "Tupí Cervecería & Terraza",
        categoria: "noche",
        intereses: ["noche", "comida", "actividades"],
        icono: "🍻",
        descripcion: "Cervecería artesanal con terraza céntrica, canillas de cervezas misioneras, picadas abundantes y música en un ambiente animado.",
        ubicacion: "Centro",
        direccion: "Av. Brasil y San Martín, Puerto Iguazú",
        coordenadas: { lat: -25.5980, lng: -54.5744 },
        tipo: "Cervecería Artesanal & Bar",
        horario: "18:00 a 02:00",
        rangoHorario: { apertura: 18, cierre: 26 }, // Cruza medianoche
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Consumo a la carta",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 2,
        alAireLibre: true,
        aptoPara: ["pareja", "amigos"],
        momentos: ["noche"],
        prioridad: 7,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757422110",
        whatsapp: "",
        web: "",
        etiquetas: ["Cerveza Artesanal", "Terraza", "Noche", "Picadas", "Música", "Centro"]
    },

    // ========================================================
    // 🍽️ GASTRONOMÍA & COMER
    // ========================================================

    {
        id: 14,
        nombre: "Aqva Restaurant",
        categoria: "comida",
        intereses: ["comida", "paseos"],
        icono: "🍽️",
        descripcion: "Referente gastronómico de Iguazú: pescados de río (Surubí, Dorado, Pacú), pastas caseras y carnes de primera calidad.",
        ubicacion: "Centro",
        direccion: "Av. Córdoba esq. Carlos Thays, Puerto Iguazú",
        coordenadas: { lat: -25.5988, lng: -54.5732 },
        tipo: "Cocina Regional y Gourmet",
        horario: "12:00 a 16:00 y 19:30 a 23:30",
        rangosHorarios: [{ apertura: 12, cierre: 16 }, { apertura: 19.5, cierre: 23.5 }],
        rangoHorario: { apertura: 12, cierre: 23.5 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Carta gourmet variada",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 1.5,
        alAireLibre: false,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mediodía", "noche"],
        prioridad: 9,
        destacado: true,
        patrocinado: false,
        promocion: "Salón climatizado y pescados frescos de río",
        prioridadComercial: 1,
        telefono: "+543757429700",
        whatsapp: "5493757505025",
        web: "https://aqvarestaurant.com/",
        etiquetas: ["Pescados de Río", "Alta Cocina", "Vinos Argentinos", "Techado"]
    },

    {
        id: 15,
        nombre: "El Quincho del Tío Querido",
        categoria: "comida",
        intereses: ["comida", "noche"],
        icono: "🥩",
        descripcion: "Tradicional parrilla argentina con carnes seleccionadas a las brasas, pescados regionales y shows de tango y folclore en vivo.",
        ubicacion: "Av. Pres. Juan D. Perón",
        direccion: "Av. Pres. Juan Domingo Perón y Caraguatay, Puerto Iguazú",
        coordenadas: { lat: -25.6025, lng: -54.5685 },
        tipo: "Parrilla Argentina & Show",
        horario: "12:00 a 15:30 y 19:30 a 23:30",
        rangosHorarios: [{ apertura: 12, cierre: 15.5 }, { apertura: 19.5, cierre: 23.5 }],
        rangoHorario: { apertura: 12, cierre: 23.5 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Carta gourmet y parrilla",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 2,
        alAireLibre: false,
        aptoPara: ["pareja", "familia", "amigos", "niños"],
        momentos: ["mediodía", "noche"],
        prioridad: 8,
        destacado: true,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757420151",
        whatsapp: "5493757420151",
        web: "https://eltioquerido.com.ar/",
        etiquetas: ["Asado", "Show en Vivo", "Tango", "Tradición", "Techado"]
    },

    {
        id: 16,
        nombre: "La Rueda 1975",
        categoria: "comida",
        intereses: ["comida", "paseos"],
        icono: "🥩",
        descripcion: "Histórico restaurante con ambiente acogedor, pastas caseras, cortes de carne vacuna y pescados de la cuenca del Paraná.",
        ubicacion: "Centro",
        direccion: "Av. Córdoba 28, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.5975, lng: -54.5738 },
        tipo: "Cocina Tradicional Argentina",
        horario: "12:00 a 15:30 y 19:30 a 23:30",
        rangosHorarios: [{ apertura: 12, cierre: 15.5 }, { apertura: 19.5, cierre: 23.5 }],
        rangoHorario: { apertura: 12, cierre: 23.5 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Carta tradicional",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 1.5,
        alAireLibre: false,
        aptoPara: ["pareja", "familia", "amigos", "niños"],
        momentos: ["mediodía", "noche"],
        prioridad: 7,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757693447",
        whatsapp: "",
        web: "",
        etiquetas: ["Clásico", "Pastas", "Carnes", "Techado", "Centro"]
    },

    {
        id: 35,
        nombre: "The Argentine Experience Iguazú",
        categoria: "comida",
        intereses: ["comida", "noche", "actividades"],
        icono: "🍷",
        descripcion: "Cena gourmet interactiva con maridaje de vinos de alta gama, preparación guiada de empanadas y cortes de carne argentina.",
        ubicacion: "Centro Gastronómico",
        direccion: "Av. Brasil 57, Puerto Iguazú",
        coordenadas: { lat: -25.5982, lng: -54.5740 },
        tipo: "Experiencia Gastronómica & Vinos",
        horario: "19:30 a 23:00 (Turno cena con reserva)",
        rangoHorario: { apertura: 19.5, cierre: 23 },
        diasApertura: [1, 2, 3, 4, 5, 6], // Martes a domingo
        precio: "Experiencia gastronómica guiada premium",
        gratuito: false,
        nivelGasto: "alto",
        duracionHoras: 2.5,
        alAireLibre: false,
        aptoPara: ["solo", "pareja", "amigos"],
        momentos: ["noche"],
        prioridad: 8,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757421800",
        whatsapp: "",
        web: "https://theargentineexperience.com/",
        etiquetas: ["Vinos Argentinos", "Empanadas", "Gourmet", "Interactivo", "Noche"]
    },

    {
        id: 36,
        nombre: "Doña María Restaurante",
        categoria: "comida",
        intereses: ["comida", "paseos"],
        icono: "🍝",
        descripcion: "Propuesta culinaria destacada por sus pastas artesanales rellenas, pescados regionales y selecta cava de vinos en el Hotel Saint George.",
        ubicacion: "Centro",
        direccion: "Av. Córdoba 148, Puerto Iguazú",
        coordenadas: { lat: -25.5981, lng: -54.5727 },
        tipo: "Cocina Regional & Pastas Artesanales",
        horario: "12:00 a 15:30 y 19:30 a 23:30",
        rangosHorarios: [{ apertura: 12, cierre: 15.5 }, { apertura: 19.5, cierre: 23.5 }],
        rangoHorario: { apertura: 12, cierre: 23.5 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Carta variada",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 1.5,
        alAireLibre: false,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mediodía", "noche"],
        prioridad: 7,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757420633",
        whatsapp: "",
        web: "",
        etiquetas: ["Pastas Caseras", "Pescados de Río", "Centro", "Techado", "Confort"]
    },

    {
        id: 38,
        nombre: "La Toscana Trattoria",
        categoria: "comida",
        intereses: ["comida", "noche"],
        icono: "🍕",
        descripcion: "Trattoria cálida y familiar con pizzas al horno de leña, pastas frescas italianas y postres caseros en el centro de la ciudad.",
        ubicacion: "Centro",
        direccion: "Av. Córdoba 235, Puerto Iguazú",
        coordenadas: { lat: -25.5985, lng: -54.5718 },
        tipo: "Trattoria Italiana & Pizzería",
        horario: "19:30 a 23:30",
        rangoHorario: { apertura: 19.5, cierre: 23.5 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Carta tradicional",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 1.5,
        alAireLibre: false,
        aptoPara: ["pareja", "familia", "amigos", "niños"],
        momentos: ["noche"],
        prioridad: 7,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757423300",
        whatsapp: "",
        web: "",
        etiquetas: ["Pizzas", "Pastas", "Centro", "Familiar", "Horno de Leña"]
    },

    {
        id: 17,
        nombre: "Jungle Restaurante",
        categoria: "comida",
        intereses: ["comida", "noche"],
        icono: "🌿",
        descripcion: "Propuesta culinaria rodeada de selva nativa, platos contemporáneos y coctelería de autor con vista a la naturaleza.",
        ubicacion: "Zona Selva",
        direccion: "Av. Tres Fronteras y Costanera, Puerto Iguazú",
        coordenadas: { lat: -25.5930, lng: -54.6040 },
        tipo: "Restaurante & Lounge de Selva",
        horario: "19:00 a 00:00",
        rangoHorario: { apertura: 19, cierre: 24 },
        diasApertura: [1, 2, 3, 4, 5, 6], // Martes a domingo
        precio: "Cocina de autor",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 1.5,
        alAireLibre: false,
        aptoPara: ["pareja", "familia", "amigos"],
        momentos: ["noche"],
        prioridad: 7,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757420600",
        whatsapp: "",
        web: "",
        etiquetas: ["Selva", "Tragos", "Ambiente", "Techado"]
    },

    // ========================================================
    // 🚗 MOVILIDAD & TRASLADOS
    // ========================================================

    {
        id: 18,
        nombre: "Colectivo Río Uruguay a Cataratas (Línea Parque)",
        categoria: "movilidad",
        intereses: ["movilidad", "naturaleza"],
        icono: "🚌",
        descripcion: "Servicio regular de autobús que conecta la Terminal de Puerto Iguazú con el ingreso al Parque Nacional cada 20 minutos.",
        ubicacion: "Terminal de Ómnibus",
        direccion: "Av. Córdoba y Av. Misiones, Terminal de Ómnibus, Puerto Iguazú",
        coordenadas: { lat: -25.5992, lng: -54.5710 },
        tipo: "Transporte Público Directo",
        horario: "Salidas cada 20 min (07:00 a 19:30)",
        rangoHorario: { apertura: 7, cierre: 20 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Boleto ida y vuelta económico",
        gratuito: false,
        nivelGasto: "economico",
        duracionHoras: 0.75,
        alAireLibre: false,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "mediodía", "tarde"],
        prioridad: 9,
        destacado: true,
        patrocinado: false,
        promocion: "Frecuencias cada 20 min desde Terminal",
        prioridadComercial: 0,
        telefono: "+543757420369",
        whatsapp: "",
        web: "https://riouruguaybus.com.ar/",
        etiquetas: ["Económico", "Directo a Cataratas", "Frecuente", "Colectivo"]
    },

    {
        id: 19,
        nombre: "Traslados al Aeropuerto de Iguazú (IGR)",
        categoria: "movilidad",
        intereses: ["movilidad"],
        icono: "✈️",
        descripcion: "Shuttles y minibuses oficiales desde y hacia el Aeropuerto Mayor Carlos Krause con paradas en hoteles y centro.",
        ubicacion: "Aeropuerto y Hoteles",
        direccion: "Ruta Nac. 101, Aeropuerto IGR, Puerto Iguazú",
        coordenadas: { lat: -25.7372, lng: -54.4733 },
        tipo: "Shuttle & Traslado Aeroportuario",
        horario: "Coordinado con todos los vuelos diarios",
        rangoHorario: { apertura: 6, cierre: 23.5 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Tarifa fija por tramo",
        gratuito: false,
        nivelGasto: "economico",
        duracionHoras: 0.75,
        alAireLibre: false,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "mediodía", "tarde", "noche"],
        prioridad: 8,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757422111",
        whatsapp: "5493757540001",
        web: "",
        etiquetas: ["Aeropuerto", "Shuttle", "Equipaje", "Traslados"]
    },

    {
        id: 20,
        nombre: "Parada Central de Taxis y Remises (Plaza San Martín)",
        categoria: "movilidad",
        intereses: ["movilidad", "tres_paises"],
        icono: "🚕",
        descripcion: "Base principal de radiotaxis con tarifas reguladas para recorridos urbanos, cruce de fronteras y traslados a atracciones.",
        ubicacion: "Plaza San Martín (Centro)",
        direccion: "Av. Victoria Aguirre y Av. Brasil, Puerto Iguazú",
        coordenadas: { lat: -25.5979, lng: -54.5742 },
        tipo: "Taxis Oficiales & Excursiones Privadas",
        horario: "Servicio 24 horas",
        rangoHorario: { apertura: 0, cierre: 24 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Tarifa regulada por taxímetro / viajes fijos",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 0.5,
        alAireLibre: false,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "mediodía", "tarde", "atardecer", "noche"],
        prioridad: 8,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757420042",
        whatsapp: "5493757420042",
        web: "",
        etiquetas: ["24 Horas", "Privado", "Confort", "Fronteras", "Taxi"]
    },

    // ========================================================
    // 🏨 ALOJAMIENTO & HOTELES
    // ========================================================

    {
        id: 21,
        nombre: "Hotel Saint George",
        categoria: "alojamiento",
        intereses: ["alojamiento", "paseos"],
        icono: "🏨",
        descripcion: "Hotel con jardines tropicales, piscina y spa ubicado estratégicamente en pleno centro gastronómico de Puerto Iguazú.",
        ubicacion: "Centro",
        direccion: "Av. Córdoba 148, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.5981, lng: -54.5727 },
        tipo: "Hotel 4 Estrellas & Spa",
        horario: "Recepción 24 horas",
        rangoHorario: { apertura: 0, cierre: 24 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Consultar tarifa por noche",
        gratuito: false,
        nivelGasto: "medio",
        duracionHoras: 1,
        alAireLibre: false,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "tarde", "noche"],
        prioridad: 8,
        destacado: true,
        patrocinado: false,
        promocion: "Ubicación céntrica privilegiada",
        prioridadComercial: 0,
        telefono: "+543757420633",
        whatsapp: "5493757420633",
        web: "https://hotelsaintgeorge.com/",
        etiquetas: ["Piscina", "Centro", "Spa", "Confort", "Hotel"]
    },

    {
        id: 22,
        nombre: "Loi Suites Iguazú Hotel",
        categoria: "alojamiento",
        intereses: ["alojamiento", "naturaleza"],
        icono: "🌿",
        descripcion: "Exclusivo resort 5 estrellas inmerso en la Reserva Selva Iryapú con puentes colgantes, piscinas y alta gastronomía.",
        ubicacion: "Reserva Selva Iryapú",
        direccion: "Selva Iryapú s/n, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.6130, lng: -54.5600 },
        tipo: "Resort 5 Estrellas de Selva",
        horario: "Recepción 24 horas",
        rangoHorario: { apertura: 0, cierre: 24 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Categoría Premium",
        gratuito: false,
        nivelGasto: "alto",
        duracionHoras: 1,
        alAireLibre: true,
        aptoPara: ["pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "tarde", "noche"],
        prioridad: 9,
        destacado: true,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 1,
        telefono: "+543757498300",
        whatsapp: "",
        web: "https://loisuites.com.ar/es/iguazu",
        etiquetas: ["Lujo", "Selva", "Piscinas", "Spa", "Resort"]
    },

    {
        id: 23,
        nombre: "Iguazú Grand Hotel & Resort",
        categoria: "alojamiento",
        intereses: ["alojamiento"],
        icono: "🏨",
        descripcion: "Hotel de lujo con suites amplias, spa, canchas de tenis y club infantil a minutos del centro de la ciudad.",
        ubicacion: "Ruta 12",
        direccion: "Ruta Nacional 12 Km 1640, Puerto Iguazú, Misiones",
        coordenadas: { lat: -25.6080, lng: -54.5630 },
        tipo: "Resort de Lujo",
        horario: "Recepción 24 horas",
        rangoHorario: { apertura: 0, cierre: 24 },
        diasApertura: [0, 1, 2, 3, 4, 5, 6],
        precio: "Categoría Superior",
        gratuito: false,
        nivelGasto: "alto",
        duracionHoras: 1,
        alAireLibre: false,
        aptoPara: ["solo", "pareja", "familia", "amigos", "niños"],
        momentos: ["mañana", "tarde", "noche"],
        prioridad: 8,
        destacado: false,
        patrocinado: false,
        promocion: null,
        prioridadComercial: 0,
        telefono: "+543757498050",
        whatsapp: "",
        web: "https://iguazugrand.com/",
        etiquetas: ["Lujo", "Kids Club", "Gastronomía", "Spa", "Hotel"]
    }

];

// ========================================================
// FUNCIONES UTILITARIAS, BÚSQUEDA Y DISPONIBILIDAD HORARIA
// ========================================================

function obtenerLugaresPorCategoria(categoria) {
    if (!categoria || categoria === "todos") return lugaresReales;
    return lugaresReales.filter(lugar => lugar.categoria.toLowerCase() === categoria.toLowerCase());
}

function obtenerLugaresPorInteres(interes) {
    if (!interes || interes === "todos") return lugaresReales;
    return lugaresReales.filter(lugar => {
        if (lugar.categoria === interes) return true;
        if (lugar.intereses && lugar.intereses.includes(interes)) return true;
        return false;
    });
}

function obtenerLugarPorIdentificador(identificador) {
    return lugaresReales.find(l => l.id === identificador || l.nombre === identificador);
}

/**
 * Evalúa si un rango horario específico está abierto en una hora dada.
 */
function comprobarRango(rango, horaNumero) {
    if (!rango) return true;
    const { apertura, cierre } = rango;
    if (apertura === 0 && cierre === 24) return true;
    if (apertura <= cierre) {
        return horaNumero >= apertura && horaNumero < cierre;
    } else {
        // Horario que cruza la medianoche (ej: 18:00 a 02:00 -> cierre: 26 o 2)
        const cierreAjustado = cierre < apertura ? cierre + 24 : cierre;
        const horaAjustada = (horaNumero < apertura && horaNumero < cierre) ? horaNumero + 24 : horaNumero;
        return horaAjustada >= apertura && horaAjustada < cierreAjustado;
    }
}

/**
 * Verifica si un lugar está abierto según una hora decimal y día específicos.
 */
function estaAbiertoEnHorario(lugar, horaNumero = (new Date().getHours() + (new Date().getMinutes() / 60)), diaSemana = new Date().getDay()) {
    // Si no tiene rango definido o no está confirmado, asumimos true para no bloquear
    if (!lugar.rangoHorario && !lugar.rangosHorarios) return true;

    // Verificar si abre el día de la semana actual
    if (lugar.diasApertura && !lugar.diasApertura.includes(diaSemana)) {
        return false;
    }

    // Verificar turnos partidos si existen (ej: Doña María / Aqva)
    if (Array.isArray(lugar.rangosHorarios) && lugar.rangosHorarios.length > 0) {
        return lugar.rangosHorarios.some(r => comprobarRango(r, horaNumero));
    }

    // Verificar rango simple
    return comprobarRango(lugar.rangoHorario, horaNumero);
}

/**
 * Obtiene el estado detallado de disponibilidad de un lugar con texto amigable para la UI.
 */
function obtenerEstadoDisponibilidad(lugar, horaNumero = (new Date().getHours() + (new Date().getMinutes() / 60)), diaSemana = new Date().getDay()) {
    if (!lugar.rangoHorario && !lugar.rangosHorarios) {
        return {
            abierto: null,
            texto: "Horario a consultar",
            badgeClass: "info",
            badgeHtml: `<span class="open-badge info">ℹ️ Horario a consultar</span>`
        };
    }

    const diaAbre = !lugar.diasApertura || lugar.diasApertura.includes(diaSemana);
    const abierto = diaAbre && estaAbiertoEnHorario(lugar, horaNumero, diaSemana);

    if (abierto) {
        return {
            abierto: true,
            texto: "Abierto ahora",
            badgeClass: "open",
            badgeHtml: `<span class="open-badge open">🟢 Abierto ahora</span>`
        };
    } else {
        const texto = diaAbre ? "Cerrado en este momento" : "Cerrado hoy";
        return {
            abierto: false,
            texto: texto,
            badgeClass: "closed",
            badgeHtml: `<span class="open-badge closed">🔴 ${texto}</span>`
        };
    }
}